// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef KEYPLE_SEPROXY_APDUREQUEST_H
#define KEYPLE_SEPROXY_APDUREQUEST_H

/************************************************************
 ApduRequest class header
 ************************************************************/

//#include "keyple/seproxy/Pkg_seproxy.h"
#include <stdint.h>


namespace keyple {
	namespace seproxy {

		/************************************************************/
		/**
		 * Class defines the elements of a single APDU command request
		 */
		class ApduRequest {
		public:

			/**
			 * Constructor
			 * Build the APDU request
			 * @param bytes 
			 * @param case4 
			 */
			ApduRequest(uint8_t inApdu[260], uint16_t inApduLength, bool inCase4 = false);

			/**
			 * Destructor
			 */
			~ApduRequest();

			/**
			 * 
			 * @return CLA 
			 */
			uint8_t getCLA();

			/**
			 * 
			 * @return INS 
			 */
			uint8_t getINS();

			/**
			 * 
			 * @return P1 
			 */
			uint8_t getP1();

			/**
			 * 
			 * @return P2 
			 */
			uint8_t getP2();

			/**
			 * 
			 * @return Lc 
			 */
			uint8_t getLc();

			/**
			 * 
			 * @return Le 
			 */
			uint8_t getLe();

			/**
			 * 
			 * @return the request Apdu
			 */
			uint8_t* getApdu();

			/**
			 * 
			 * @return the length of the request Apdu
			 */
			uint16_t getApduLength();

			/**
			 * 
			 * @return case4 the case4 flag.
			 */
			bool isCase4();

			/**
			 * 
			 * @return bytes the data of APDU response
			 */
			uint8_t* getData();

		private:

			/**
			 * a ‘case 4’ flag in order to explicitly specify, if it’s expected that the APDU command returns data.
			 */
			bool case4;

			/**
			 * an array of the bytes of an Apdu request
			 */
			uint8_t data[260];

			uint16_t dataLength = 0;

			uint8_t CLA;
			uint8_t INS;
			uint8_t P1;
			uint8_t P2;
			uint8_t Lc = 0;
			uint8_t Le = 0;

			uint8_t apdu[260];

			uint16_t apduLength = 0;
		};
	/************************************************************/
	/* External declarations (package visibility)               */
	/************************************************************/

	/* Inline functions                                         */

	} // of namespace seproxy
} // of namespace keyple

/************************************************************
 End of ApduRequest class header
 ************************************************************/

#endif
