// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef KEYPLE_SEPROXY_OBSERVABLEREADER_H
#define KEYPLE_SEPROXY_OBSERVABLEREADER_H

/************************************************************
 ObservableReader class header
 ************************************************************/

//#include "keyple/seproxy/Pkg_seproxy.h"

#include <list>

#include "ReaderObserver.h"

namespace keyple {
namespace seproxy {

/************************************************************/
/**
 * 
 */
class ObservableReader {
public:

	ObservableReader();

	~ObservableReader();

	/**
	 * 
	 * @param callback 
	 */
	void attachObserver(ReaderObserver* /*in*/callback);

	/**
	 * 
	 * @param callback 
	 */
	void detachObserver(ReaderObserver* /*in*/callback);

private:
	/**
	 * 
	 */
	std::list<ReaderObserver> readerObservers;
};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace seproxy
} // of namespace keyple

/************************************************************
 End of ObservableReader class header
 ************************************************************/

#endif
