// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef KEYPLE_SEPROXY_READERSPLUGIN_H
#define KEYPLE_SEPROXY_READERSPLUGIN_H

/************************************************************
 ReadersPlugin class header
 ************************************************************/

#include "ProxyReader.hpp"

#include <string>
#include <list>

namespace keyple {

	namespace seproxy {

		/************************************************************/
		/**
		 * Class ReadersPlugin to define Readers Plugin
		 */
		class ReadersPlugin {
		public:

			ReadersPlugin(void* inProxyContext, uint32_t inPluginType);
			/**
			 * 
			 */
			~ReadersPlugin();

			/**
			 * 
			 * @return the unique name of the readers’ plugin
			 */
			std::string getName();

			/**
			 * 
			 * @return the list of available connected SE readers for the selected plugin
			 */
			std::list<ProxyReader>* getReaders();

		private:
			/**
			 * Name of the readers' plugin
			 */
			std::string pluginName;

			/**
			 * List of available connected SE readers for the selected plugin
			 */
			std::list<ProxyReader> proxyReaderList;

			void *proxyContext;

			void *pluginContext;
		};
		/************************************************************/
		/* External declarations (package visibility)               */
		/************************************************************/

		/* Inline functions                                         */

	} // of namespace seproxy

} // of namespace keyple

/************************************************************
 End of ReadersPlugin class header
 ************************************************************/

#endif
