// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef KEYPLE_SEPROXY_READEROBSERVER_H
#define KEYPLE_SEPROXY_READEROBSERVER_H

/************************************************************
 ReaderObserver class header
 ************************************************************/

//#include "keyple/seproxy/Pkg_seproxy.h"

#include "ReaderEvent.h"

namespace keyple {
namespace seproxy {

/************************************************************/
/**
 * Abstract class optionnaly implementable by ticketing applications
 */
class ReaderObserver {
public:

	virtual ~ReaderObserver();

	/**
	 * 
	 * @param event 
	 */
	virtual void notify(ReaderEvent* /*in*/event) = 0;

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

} // of namespace seproxy
} // of namespace keyple

/************************************************************
 End of ReaderObserver class header
 ************************************************************/

#endif
